# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab751af12b0875381077543ec2a902cd400530d776c742f289af15d3b61409efc8b7661fa41edc0f2cb1572bf6a9094702786a59fc4bd14487cb0487427841b5

test:
  secret_key_base: 4ed7d5c807f70b165c210937f9ec6eaea2495949d859e9b565e974bbe9764d1e9abdf77f10217bf39752528bbd479bb13b0c2956aba0fa444db2ea84662f4388

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
